### ISSUE TITLE
Support Terraform Files (.tf / .tfvars)

### ISSUE THREAD

**Issue by Rick-McClatchie** [pouyakary/comment-vscode#10]
Hi,

any way you could support Terraform Files? 

Comments take the Form of either // or # ([Terraform Docs](https://www.terraform.io/docs/configuration/syntax.html#comments)) 

But I think the # is the preffered method to comment.

Thanks for this really cool project!

**Comment by pouyakary** [comment]
Support added in `11.0.1` :*
