### ISSUE TITLE
Make header comment capital

### ISSUE THREAD

**Issue by lguerard** [pouyakary/comment-vscode#19]
Hi all,

Since the new version, the header comment are no longer capitalized. I tried looking into the settings to find how to do this but couldn't.

Is this on purpose ? If so, is there any way to add this as an option ?

Thanks for your help !

**Comment by pouyakary** [comment]
Have you tried:

```
"comment": {
    "legacy":      false
},
```

For some reason, `vsce` has logged off me and won't let me login, so I have a lots of hot fixes for comment but I can't ship them :(

**Comment by lguerard** [comment]
Hi ! 

Yes I have this in my JSON settings file. Weirdly enough, it looks slightly dimmer as if not used, but it's there and doesn't do any difference :/

**Comment by pouyakary** [comment]
Oh that's a shame... Hope I can fix it soon...

**Comment by pouyakary** [comment]
@lguerard hopefully it's fixed with the new settings.

**Comment by lguerard** [comment]
Can confirm it's fixed, thanks a lot !

**Comment by pouyakary** [comment]
Awesome and you're welcome!
